"""
Stage agents pinned to a model version.

Claude Code's Agent tool only takes a model family (opus, sonnet, haiku,
fable), so /sdlc can't pass a version like claude-opus-4-5 when it starts a
stage. An agent file's own `model:` line does take a version, though, and a
project's .claude/agents/<name>.md overrides the user-level agent of the same
name. So for each stage whose `models` value in .sdlc/config.json is a version
rather than a family, sdlc writes a copy of the engine's agent file into the
project with that version on its `model:` line.

The copies are generated: each carries GENERATED_MARKER, is rewritten whenever
the engine's file or the setting changes, is removed when the stage goes back
to a family or its own model, and is listed in .claude/agents/.gitignore (the
engine that produced it is this machine's, not the team's). A file without the
marker is a person's own and is never touched.

Claude Code reads agent files when a session starts, so a copy written or
changed here applies from the next session.
"""

import re
from pathlib import Path

import config

ENGINE_AGENTS_DIR = config.ENGINE_ROOT / "claude" / "agents"
GENERATED_MARKER = "# Generated by sdlc"
GITIGNORE_HEADER = "# sdlc: generated agent copies (model versions from .sdlc/config.json)"


def project_agents_dir(root=None):
    return Path(root or config.PROJECT_ROOT) / ".claude" / "agents"


def pinned():
    """{subagent name: (stage, model version)} for stages pinned to a version."""
    result = {}
    for stage, subagent in config.AGENT_SUBAGENTS.items():
        model = config.model_for(stage)
        if model and not config.is_model_family(model):
            result[subagent] = (stage, model)
    return result


def is_generated(path):
    try:
        return GENERATED_MARKER in path.read_text().split("\n---", 1)[0]
    except (OSError, UnicodeDecodeError):
        return False


def render(subagent, stage, model):
    """The engine's agent file with `model:` set to the version and the marker added."""
    source = ENGINE_AGENTS_DIR / f"{subagent}.md"
    text = source.read_text()
    match = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not match:
        raise ValueError(f"{source} has no frontmatter")
    lines = [line for line in match.group(1).split("\n") if not re.match(r"model\s*:", line)]
    marker = (f"{GENERATED_MARKER} from {source} because .sdlc/config.json pins {stage} to {model}.\n"
              f"# Don't edit: sdlc rewrites it. Change `models` in .sdlc/config.json instead.")
    return f"---\n{marker}\n" + "\n".join(lines) + f"\nmodel: {model}\n---\n" + text[match.end():]


def sync(root=None):
    """
    Bring the project's generated agent copies in line with `models`. Returns
    (changes, warnings) as lines for people to read: what was written or
    removed, and stages that couldn't be pinned.
    """
    folder = project_agents_dir(root)
    wanted = pinned()
    changes, warnings = [], []

    for subagent, (stage, model) in wanted.items():
        path = folder / f"{subagent}.md"
        if path.exists() and not is_generated(path):
            warnings.append(f"{stage}: not pinned to {model}, because {path} is the project's own agent file "
                           f"(set its model: line yourself, or remove it)")
            continue
        content = render(subagent, stage, model)
        if path.is_file() and path.read_text() == content:
            continue
        folder.mkdir(parents=True, exist_ok=True)
        existed = path.exists()
        path.write_text(content)
        changes.append(f"{stage}: {'updated' if existed else 'wrote'} {path} ({model})")

    if folder.is_dir():
        for path in sorted(folder.glob("sdlc-*.md")):
            if path.stem not in wanted and is_generated(path):
                path.unlink()
                changes.append(f"removed {path} (no longer pinned to a version)")

    _write_gitignore(folder, [f"{name}.md" for name in wanted
                              if is_generated(folder / f"{name}.md")])
    return changes, warnings


def _write_gitignore(folder, names):
    """Keep our section of .claude/agents/.gitignore listing exactly `names`; leave other lines."""
    path = folder / ".gitignore"
    kept, ours = [], False
    if path.is_file():
        for line in path.read_text().splitlines():
            if line == GITIGNORE_HEADER:
                ours = True
            elif ours and line.startswith("sdlc-") and line.endswith(".md"):
                continue
            else:
                ours = False
                kept.append(line)
    while kept and not kept[-1].strip():
        kept.pop()
    lines = kept + ([""] if kept and names else []) + ([GITIGNORE_HEADER] + sorted(names) if names else [])
    if lines:
        content = "\n".join(lines) + "\n"
        if not path.is_file() or path.read_text() != content:
            path.write_text(content)
    elif path.is_file():
        path.unlink()
